AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-cloudwatch-retention-bot
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  RoleName:
    Type: String
    Default: OrganizationAccountAccessRole
  RetentionTime:
    Type: Number
    Description: The number of days set as retention. 0 is never expire, maximum is 10 years
    Default: 365
    AllowedValues:
      - 0
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
  OutOfScopeAccounts:
    Type: String
    Description: Comma-separated list of accounts which should not be processed. Example could be out of bounds accounts where central role doesn't have access.
    Default: 111222333444,555666777888
  SessionName:
    Type: String
    Description: The name of the session which will appear in Cloudtrail with the API call
    Default: CloudwatchRetentionBot

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM Role used by the CloudwatchRetentionSetterBot
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess

  cloudwatchRetentionSetter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/cloudwatch.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      MemorySize: 512
      Timeout: 900
      Description: Iterates over AWS accounts in search for CloudWatch logs to set a specified retention policy on
      Environment:
        Variables:
          ROLENAME: !Ref RoleName
          OUT_OF_SCOPE_ACCOUNTS: !Ref OutOfScopeAccounts
          SESSION_NAME: !Ref SessionName
          RETENTIONTIME: !Ref RetentionTime


